//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.18 at 05:13:00 ÏÂÎç CST 
//


package hp.fcs.webservicesfw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:HP:FCS:WebServicesFW}CMAIP"/>
 *         &lt;element ref="{urn:HP:FCS:WebServicesFW}VFWNAME"/>
 *         &lt;element ref="{urn:HP:FCS:WebServicesFW}ACLs"/>
 *         &lt;element ref="{urn:HP:FCS:WebServicesFW}NATs"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cmaip",
    "vfwname",
    "acLs",
    "naTs"
})
@XmlRootElement(name = "Device")
public class Device {

    @XmlElement(name = "CMAIP", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String cmaip;
    @XmlElement(name = "VFWNAME", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String vfwname;
    @XmlElement(name = "ACLs", required = true)
    protected ACLs acLs;
    @XmlElement(name = "NATs", required = true)
    protected NATs naTs;

    /**
     * Gets the value of the cmaip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCMAIP() {
        return cmaip;
    }

    /**
     * Sets the value of the cmaip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMAIP(String value) {
        this.cmaip = value;
    }

    /**
     * Gets the value of the vfwname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVFWNAME() {
        return vfwname;
    }

    /**
     * Sets the value of the vfwname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVFWNAME(String value) {
        this.vfwname = value;
    }

    /**
     * Gets the value of the acLs property.
     * 
     * @return
     *     possible object is
     *     {@link ACLs }
     *     
     */
    public ACLs getACLs() {
        return acLs;
    }

    /**
     * Sets the value of the acLs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACLs }
     *     
     */
    public void setACLs(ACLs value) {
        this.acLs = value;
    }

    /**
     * Gets the value of the naTs property.
     * 
     * @return
     *     possible object is
     *     {@link NATs }
     *     
     */
    public NATs getNATs() {
        return naTs;
    }

    /**
     * Sets the value of the naTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link NATs }
     *     
     */
    public void setNATs(NATs value) {
        this.naTs = value;
    }

}
