//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.18 at 05:13:00 ÏÂÎç CST 
//


package hp.fcs.webservicesfw;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hp.fcs.webservicesfw package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Status_QNAME = new QName("urn:HP:FCS:WebServicesFW", "status");
    private final static QName _CMAIP_QNAME = new QName("urn:HP:FCS:WebServicesFW", "CMAIP");
    private final static QName _Message_QNAME = new QName("urn:HP:FCS:WebServicesFW", "message");
    private final static QName _WorkorderID_QNAME = new QName("urn:HP:FCS:WebServicesFW", "workorderID");
    private final static QName _VFWNAME_QNAME = new QName("urn:HP:FCS:WebServicesFW", "VFWNAME");
    private final static QName _Action_QNAME = new QName("urn:HP:FCS:WebServicesFW", "action");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hp.fcs.webservicesfw
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ACLs }
     * 
     */
    public ACLs createACLs() {
        return new ACLs();
    }

    /**
     * Create an instance of {@link ACL }
     * 
     */
    public ACL createACL() {
        return new ACL();
    }

    /**
     * Create an instance of {@link NATs }
     * 
     */
    public NATs createNATs() {
        return new NATs();
    }

    /**
     * Create an instance of {@link FWConfig }
     * 
     */
    public FWConfig createFWConfig() {
        return new FWConfig();
    }

    /**
     * Create an instance of {@link Device }
     * 
     */
    public Device createDevice() {
        return new Device();
    }

    /**
     * Create an instance of {@link NAT }
     * 
     */
    public NAT createNAT() {
        return new NAT();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:HP:FCS:WebServicesFW", name = "status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:HP:FCS:WebServicesFW", name = "CMAIP")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCMAIP(String value) {
        return new JAXBElement<String>(_CMAIP_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:HP:FCS:WebServicesFW", name = "message")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMessage(String value) {
        return new JAXBElement<String>(_Message_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:HP:FCS:WebServicesFW", name = "workorderID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createWorkorderID(String value) {
        return new JAXBElement<String>(_WorkorderID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:HP:FCS:WebServicesFW", name = "VFWNAME")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createVFWNAME(String value) {
        return new JAXBElement<String>(_VFWNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:HP:FCS:WebServicesFW", name = "action")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAction(String value) {
        return new JAXBElement<String>(_Action_QNAME, String.class, null, value);
    }

}
